# Generated by Django 4.0 on 2021-12-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.AddField(
            model_name='card',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
