# Generated by Django 4.0 on 2021-12-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='spcolor',
            field=models.CharField(default='0000ff', max_length=200),
            preserve_default=False,
        ),
    ]
