# Generated by Django 4.0 on 2021-12-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_card_created_at_card_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mood',
            field=models.CharField(default='red', max_length=200),
            preserve_default=False,
        ),
    ]
